const BASE_URL = "https://pipl-ai.mchub.io";
const CLIENT_ID_GCP = "610108940766-nc7p0752n7u9qq5e6clejoai6o5ue031.apps.googleusercontent.com";
const DATA_SPAM = [
  { highlight: /access/gi, keyword: "Access", category: "urgency" },
  { highlight: /access now/gi, keyword: "Access now", category: "urgency" },
  { highlight: /act/gi, keyword: "Act", category: "urgency" },
  { highlight: /act immediately/gi, keyword: "Act immediately", category: "urgency" },
  { highlight: /act now/gi, keyword: "Act now", category: "urgency" },
  { highlight: /act now!/gi, keyword: "Act now!", category: "urgency" },
  { highlight: /action/gi, keyword: "Action", category: "urgency" },
  { highlight: /action required/gi, keyword: "Action required", category: "urgency" },
  { highlight: /apply here/gi, keyword: "Apply here", category: "urgency" },
  { highlight: /apply now/gi, keyword: "Apply now", category: "urgency" },
  { highlight: /apply now!/gi, keyword: "Apply now!", category: "urgency" },
  { highlight: /apply online/gi, keyword: "Apply online", category: "urgency" },
  { highlight: /asap/gi, keyword: "ASAP", category: "urgency" },
  { highlight: /become a member/gi, keyword: "Become a member", category: "urgency" },
  { highlight: /before it's too late/gi, keyword: "Before it's too late", category: "urgency" },
  { highlight: /being a member/gi, keyword: "Being a member", category: "urgency" },
  { highlight: /buy/gi, keyword: "Buy", category: "urgency" },
  { highlight: /buy direct/gi, keyword: "Buy direct", category: "urgency" },
  { highlight: /buy now/gi, keyword: "Buy now", category: "urgency" },
  { highlight: /buy today/gi, keyword: "Buy today", category: "urgency" },
  { highlight: /call/gi, keyword: "Call", category: "urgency" },
  { highlight: /call free/gi, keyword: "Call free", category: "urgency" },
  { highlight: /call (free|now)/gi, keyword: "Call free/now", category: "urgency" },
  { highlight: /call me/gi, keyword: "Call me", category: "urgency" },
  { highlight: /call now/gi, keyword: "Call now", category: "urgency" },
  { highlight: /call now!/gi, keyword: "Call now!", category: "urgency" },
  {
    highlight: /can we have a minute of your time\?/gi,
    keyword: "Can we have a minute of your time?",
    category: "urgency",
  },
  { highlight: /cancel now/gi, keyword: "Cancel now", category: "urgency" },
  {
    highlight: /cancellation required/gi,
    keyword: "Cancellation required",
    category: "urgency",
  },
  { highlight: /claim now/gi, keyword: "Claim now", category: "urgency" },
  { highlight: /click/gi, keyword: "Click", category: "urgency" },
  { highlight: /click below/gi, keyword: "Click below", category: "urgency" },
  { highlight: /click here/gi, keyword: "Click here", category: "urgency" },
  { highlight: /click me to download/gi, keyword: "Click me to download", category: "urgency" },
  { highlight: /click now/gi, keyword: "Click now", category: "urgency" },
  { highlight: /click this link/gi, keyword: "Click this link", category: "urgency" },
  { highlight: /click to get/gi, keyword: "Click to get", category: "urgency" },
  { highlight: /click to remove/gi, keyword: "Click to remove", category: "urgency" },
  {
    highlight: /contact us immediately/gi,
    keyword: "Contact us immediately",
    category: "urgency",
  },
  { highlight: /deal ending soon/gi, keyword: "Deal ending soon", category: "urgency" },
  { highlight: /do it now/gi, keyword: "Do it now", category: "urgency" },
  { highlight: /do it today/gi, keyword: "Do it today", category: "urgency" },
  { highlight: /don't delete/gi, keyword: "Don't delete", category: "urgency" },
  { highlight: /don't hesitate/gi, keyword: "Don't hesitate", category: "urgency" },
  { highlight: /don't waste time/gi, keyword: "Don't waste time", category: "urgency" },
  { highlight: /don’t delete/gi, keyword: "Don’t delete", category: "urgency" },
  { highlight: /exclusive deal/gi, keyword: "Exclusive deal", category: "urgency" },
  { highlight: /expire/gi, keyword: "Expire", category: "urgency" },
  { highlight: /expires today/gi, keyword: "Expires today", category: "urgency" },
  { highlight: /final call/gi, keyword: "Final call", category: "urgency" },
  { highlight: /for instant access/gi, keyword: "For instant access", category: "urgency" },
  { highlight: /for only/gi, keyword: "For Only", category: "urgency" },
  { highlight: /for you/gi, keyword: "For you", category: "urgency" },
  {
    highlight: /friday before [holiday]/gi,
    keyword: "Friday before [holiday]",
    category: "urgency",
  },
  { highlight: /get it away/gi, keyword: "Get it away", category: "urgency" },
  { highlight: /get it now/gi, keyword: "Get it now", category: "urgency" },
  { highlight: /get now/gi, keyword: "Get now", category: "urgency" },
  { highlight: /get paid/gi, keyword: "Get paid", category: "urgency" },
  { highlight: /get started/gi, keyword: "Get started", category: "urgency" },
  { highlight: /get started now/gi, keyword: "Get started now", category: "urgency" },
  { highlight: /great offer/gi, keyword: "Great offer", category: "urgency" },
  { highlight: /hurry up/gi, keyword: "Hurry up", category: "urgency" },
  { highlight: /immediately/gi, keyword: "Immediately", category: "urgency" },
  { highlight: /info you requested/gi, keyword: "Info you requested", category: "urgency" },
  {
    highlight: /information you requested/gi,
    keyword: "Information you requested",
    category: "urgency",
  },
  { highlight: /instant/gi, keyword: "Instant", category: "urgency" },
  { highlight: /limited time/gi, keyword: "Limited time", category: "urgency" },
  { highlight: /new customers only/gi, keyword: "New customers only", category: "urgency" },
  { highlight: /now/gi, keyword: "Now", category: "urgency" },
  { highlight: /now only/gi, keyword: "Now only", category: "urgency" },
  { highlight: /offer expires/gi, keyword: "Offer expires", category: "urgency" },
  { highlight: /once in lifetime/gi, keyword: "Once in lifetime", category: "urgency" },
  { highlight: /only/gi, keyword: "Only", category: "urgency" },
  { highlight: /order now/gi, keyword: "Order now", category: "urgency" },
  { highlight: /order today/gi, keyword: "Order today", category: "urgency" },
  { highlight: /please read/gi, keyword: "Please read", category: "urgency" },
  { highlight: /purchase now/gi, keyword: "Purchase now", category: "urgency" },
  { highlight: /sign up free/gi, keyword: "Sign up free", category: "urgency" },
  { highlight: /sign up free today/gi, keyword: "Sign up free today", category: "urgency" },
  { highlight: /supplies are limited/gi, keyword: "Supplies are limited", category: "urgency" },
  { highlight: /take action/gi, keyword: "Take action", category: "urgency" },
  { highlight: /take action now/gi, keyword: "Take action now", category: "urgency" },
  { highlight: /this won’t last/gi, keyword: "This won’t last", category: "urgency" },
  { highlight: /time limited/gi, keyword: "Time limited", category: "urgency" },
  { highlight: /today/gi, keyword: "Today", category: "urgency" },
  { highlight: /top urgent/gi, keyword: "Top urgent", category: "urgency" },
  { highlight: /trial/gi, keyword: "Trial", category: "urgency" },
  { highlight: /urgent/gi, keyword: "Urgent", category: "urgency" },
  {
    highlight: /what are you waiting for\?/gi,
    keyword: "What are you waiting for?",
    category: "urgency",
  },
  { highlight: /while supplies last/gi, keyword: "While supplies last", category: "urgency" },
  { highlight: /you are a winner/gi, keyword: "You are a winner", category: "urgency" },
  { highlight: /0 down/gi, keyword: "0 down", category: "shady" },
  { highlight: /all/gi, keyword: "All", category: "shady" },
  { highlight: /all natural/gi, keyword: "All natural", category: "shady" },
  { highlight: /all (natural|new)/gi, keyword: "All natural/new", category: "shady" },
  { highlight: /all new/gi, keyword: "All new", category: "shady" },
  { highlight: /all-natural/gi, keyword: "All-natural", category: "shady" },
  { highlight: /all-new/gi, keyword: "All-new", category: "shady" },
  { highlight: /allowance/gi, keyword: "Allowance", category: "shady" },
  { highlight: /as seen on/gi, keyword: "As seen on", category: "shady" },
  { highlight: /as seen on oprah/gi, keyword: "As seen on Oprah", category: "shady" },
  { highlight: /at no cost/gi, keyword: "At no cost", category: "shady" },
  { highlight: /auto email removal/gi, keyword: "Auto email removal", category: "shady" },
  { highlight: /avoice bankruptcy/gi, keyword: "Avoice bankruptcy", category: "shady" },
  { highlight: /avoid/gi, keyword: "Avoid", category: "shady" },
  { highlight: /beneficial offer/gi, keyword: "Beneficial offer", category: "shady" },
  { highlight: /beneficiary/gi, keyword: "Beneficiary", category: "shady" },
  { highlight: /bill 1618/gi, keyword: "Bill 1618", category: "shady" },
  { highlight: /brand new pager/gi, keyword: "Brand new pager", category: "shady" },
  { highlight: /bulk email/gi, keyword: "Bulk email", category: "shady" },
  { highlight: /buying judgements/gi, keyword: "Buying judgements", category: "shady" },
  { highlight: /buying judgments/gi, keyword: "Buying judgments", category: "shady" },
  { highlight: /cable converter/gi, keyword: "Cable converter", category: "shady" },
  { highlight: /calling creditors/gi, keyword: "Calling creditors", category: "shady" },
  { highlight: /can you help us\?/gi, keyword: "Can you help us?", category: "shady" },
  { highlight: /cancel at any time/gi, keyword: "Cancel at any time", category: "shady" },
  { highlight: /cannot be combined/gi, keyword: "Cannot be combined", category: "shady" },
  { highlight: /celebrity/gi, keyword: "Celebrity", category: "shady" },
  {
    highlight: /cell phone cancer scam/gi,
    keyword: "Cell phone cancer scam",
    category: "shady",
  },
  { highlight: /certified/gi, keyword: "Certified", category: "shady" },
  { highlight: /chance/gi, keyword: "Chance", category: "shady" },
  { highlight: /cheap/gi, keyword: "Cheap", category: "shady" },
  { highlight: /cheap meds/gi, keyword: "Cheap meds", category: "shady" },
  { highlight: /cialis/gi, keyword: "Cialis", category: "shady" },
  { highlight: /claims/gi, keyword: "Claims", category: "shady" },
  {
    highlight: /claims not to be selling anything/gi,
    keyword: "Claims not to be selling anything",
    category: "shady",
  },
  {
    highlight: /claims to be in accordance with some spam law/gi,
    keyword: "Claims to be in accordance with some spam law",
    category: "shady",
  },
  { highlight: /claims to be legal/gi, keyword: "Claims to be legal", category: "shady" },
  { highlight: /clearance/gi, keyword: "Clearance", category: "shady" },
  { highlight: /collect/gi, keyword: "Collect", category: "shady" },
  { highlight: /collect child support/gi, keyword: "Collect child support", category: "shady" },
  { highlight: /compare/gi, keyword: "Compare", category: "shady" },
  { highlight: /compare now/gi, keyword: "Compare now", category: "shady" },
  { highlight: /compare online/gi, keyword: "Compare online", category: "shady" },
  { highlight: /compare rates/gi, keyword: "Compare rates", category: "shady" },
  {
    highlight: /compete for your business/gi,
    keyword: "Compete for your business",
    category: "shady",
  },
  { highlight: /confidentiality/gi, keyword: "Confidentiality", category: "shady" },
  { highlight: /congratulations/gi, keyword: "Congratulations", category: "shady" },
  {
    highlight: /consolidate debt and credit/gi,
    keyword: "Consolidate debt and credit",
    category: "shady",
  },
  { highlight: /consolidate your debt/gi, keyword: "Consolidate your debt", category: "shady" },
  { highlight: /copy accurately/gi, keyword: "Copy accurately", category: "shady" },
  { highlight: /copy dvds/gi, keyword: "Copy DVDs", category: "shady" },
  { highlight: /covid/gi, keyword: "COVID", category: "shady" },
  { highlight: /cures/gi, keyword: "Cures", category: "shady" },
  { highlight: /cures baldness/gi, keyword: "Cures baldness", category: "shady" },
  { highlight: /diagnostic/gi, keyword: "Diagnostic", category: "shady" },
  { highlight: /diagnostics/gi, keyword: "DIAGNOSTICS", category: "shady" },
  { highlight: /diet/gi, keyword: "Diet", category: "shady" },
  {
    highlight: /dig up dirt on friends/gi,
    keyword: "Dig up dirt on friends",
    category: "shady",
  },
  { highlight: /direct email/gi, keyword: "Direct email", category: "shady" },
  { highlight: /direct marketing/gi, keyword: "Direct marketing", category: "shady" },
  { highlight: /eliminate debt/gi, keyword: "Eliminate debt", category: "shady" },
  { highlight: /explode your business/gi, keyword: "Explode your business", category: "shady" },
  { highlight: /fast viagra delivery/gi, keyword: "Fast viagra delivery", category: "shady" },
  { highlight: /finance/gi, keyword: "Finance", category: "shady" },
  { highlight: /financial/gi, keyword: "Financial", category: "shady" },
  { highlight: /financial advice/gi, keyword: "Financial advice", category: "shady" },
  {
    highlight: /financial independence/gi,
    keyword: "Financial independence",
    category: "shady",
  },
  {
    highlight: /financially independent/gi,
    keyword: "Financially independent",
    category: "shady",
  },
  {
    highlight: /for new customers only/gi,
    keyword: "For new customers only",
    category: "shady",
  },
  { highlight: /foreclosure/gi, keyword: "Foreclosure", category: "shady" },
  { highlight: /free/gi, keyword: "Free", category: "shady" },
  {
    highlight: /free (access|money|gift)/gi,
    keyword: "Free access/money/gift",
    category: "shady",
  },
  { highlight: /free bonus/gi, keyword: "Free bonus", category: "shady" },
  { highlight: /free cell phone/gi, keyword: "Free cell phone", category: "shady" },
  { highlight: /free dvd/gi, keyword: "Free DVD", category: "shady" },
  { highlight: /free grant money/gi, keyword: "Free grant money", category: "shady" },
  { highlight: /free information/gi, keyword: "Free information", category: "shady" },
  { highlight: /free installation/gi, keyword: "Free installation", category: "shady" },
  { highlight: /free instant/gi, keyword: "Free Instant", category: "shady" },
  { highlight: /free iphone/gi, keyword: "Free iPhone", category: "shady" },
  { highlight: /free laptop/gi, keyword: "Free laptop", category: "shady" },
  { highlight: /free leads/gi, keyword: "Free leads", category: "shady" },
  { highlight: /free macbook/gi, keyword: "Free Macbook", category: "shady" },
  { highlight: /free offer/gi, keyword: "Free offer", category: "shady" },
  { highlight: /free priority mail/gi, keyword: "Free priority mail", category: "shady" },
  { highlight: /free sample/gi, keyword: "Free sample", category: "shady" },
  { highlight: /free website/gi, keyword: "Free website", category: "shady" },
  { highlight: /free!/gi, keyword: "Free!", category: "shady" },
  { highlight: /get/gi, keyword: "Get", category: "shady" },
  { highlight: /gift card/gi, keyword: "Gift card", category: "shady" },
  { highlight: /gift certificate/gi, keyword: "Gift certificate", category: "shady" },
  { highlight: /gift included/gi, keyword: "Gift included", category: "shady" },
  { highlight: /give it away/gi, keyword: "Give it away", category: "shady" },
  { highlight: /giving away/gi, keyword: "Giving away", category: "shady" },
  { highlight: /giving it away/gi, keyword: "Giving it away", category: "shady" },
  { highlight: /gold/gi, keyword: "Gold", category: "shady" },
  { highlight: /great/gi, keyword: "Great", category: "shady" },
  { highlight: /great deal/gi, keyword: "Great deal", category: "shady" },
  { highlight: /greetings of the day/gi, keyword: "Greetings of the day", category: "shady" },
  { highlight: /growth hormone/gi, keyword: "Growth hormone", category: "shady" },
  { highlight: /guarantee/gi, keyword: "Guarantee", category: "shady" },
  { highlight: /guaranteed deposit/gi, keyword: "Guaranteed deposit", category: "shady" },
  { highlight: /guaranteed income/gi, keyword: "Guaranteed income", category: "shady" },
  { highlight: /guaranteed payment/gi, keyword: "Guaranteed payment", category: "shady" },
  {
    highlight: /have you been turned down\?/gi,
    keyword: "Have you been turned down?",
    category: "shady",
  },
  {
    highlight: /hello (with no name included)/gi,
    keyword: "Hello (with no name included)",
    category: "shady",
  },
  { highlight: /hidden charges/gi, keyword: "Hidden charges", category: "shady" },
  { highlight: /hidden costs/gi, keyword: "Hidden costs", category: "shady" },
  { highlight: /hidden fees/gi, keyword: "Hidden fees", category: "shady" },
  { highlight: /high score/gi, keyword: "High score", category: "shady" },
  { highlight: /home based business/gi, keyword: "Home based business", category: "shady" },
  { highlight: /home mortgage/gi, keyword: "Home mortgage", category: "shady" },
  { highlight: /human/gi, keyword: "Human", category: "shady" },
  { highlight: /human growth hormone/gi, keyword: "Human growth hormone", category: "shady" },
  {
    highlight: /if only it were that easy/gi,
    keyword: "If only it were that easy",
    category: "shady",
  },
  { highlight: /important information/gi, keyword: "Important information", category: "shady" },
  {
    highlight: /important notification/gi,
    keyword: "Important notification",
    category: "shady",
  },
  { highlight: /instant weight loss/gi, keyword: "Instant weight loss", category: "shady" },
  { highlight: /insurance lose weight/gi, keyword: "Insurance Lose weight", category: "shady" },
  { highlight: /internet marketing/gi, keyword: "Internet marketing", category: "shady" },
  { highlight: /investment decision/gi, keyword: "Investment decision", category: "shady" },
  { highlight: /invoice/gi, keyword: "Invoice", category: "shady" },
  { highlight: /it’s effective/gi, keyword: "It’s effective", category: "shady" },
  { highlight: /job alert/gi, keyword: "Job alert", category: "shady" },
  { highlight: /junk/gi, keyword: "Junk", category: "shady" },
  { highlight: /lambo/gi, keyword: "Lambo", category: "shady" },
  { highlight: /laser printer/gi, keyword: "Laser printer", category: "shady" },
  { highlight: /last day/gi, keyword: "Last Day", category: "shady" },
  { highlight: /legal/gi, keyword: "Legal", category: "shady" },
  { highlight: /legal notice/gi, keyword: "Legal notice", category: "shady" },
  { highlight: /life/gi, keyword: "Life", category: "shady" },
  { highlight: /life insurance/gi, keyword: "Life insurance", category: "shady" },
  { highlight: /lifetime access/gi, keyword: "Lifetime access", category: "shady" },
  { highlight: /lifetime deal/gi, keyword: "Lifetime deal", category: "shady" },
  { highlight: /limited/gi, keyword: "Limited", category: "shady" },
  { highlight: /limited amount/gi, keyword: "Limited amount", category: "shady" },
  { highlight: /limited number/gi, keyword: "Limited number", category: "shady" },
  { highlight: /limited offer/gi, keyword: "Limited offer", category: "shady" },
  { highlight: /limited supply/gi, keyword: "Limited supply", category: "shady" },
  { highlight: /limited time offer/gi, keyword: "Limited time offer", category: "shady" },
  { highlight: /limited time only/gi, keyword: "Limited time only", category: "shady" },
  { highlight: /loan/gi, keyword: "Loan", category: "shady" },
  {
    highlight: /long distance phone number/gi,
    keyword: "Long distance phone number",
    category: "shady",
  },
  {
    highlight: /long distance phone offer/gi,
    keyword: "Long distance phone offer",
    category: "shady",
  },
  { highlight: /lose weight/gi, keyword: "Lose weight", category: "shady" },
  { highlight: /lose weight fast/gi, keyword: "Lose weight fast", category: "shady" },
  { highlight: /lose weight spam/gi, keyword: "Lose weight spam", category: "shady" },
  { highlight: /lottery/gi, keyword: "Lottery", category: "shady" },
  { highlight: /lower interest rate/gi, keyword: "Lower interest rate", category: "shady" },
  { highlight: /lower interest rates/gi, keyword: "Lower interest rates", category: "shady" },
  { highlight: /lower monthly payment/gi, keyword: "Lower monthly payment", category: "shady" },
  {
    highlight: /lower your mortgage rate/gi,
    keyword: "Lower your mortgage rate",
    category: "shady",
  },
  {
    highlight: /lowest insurance rates/gi,
    keyword: "Lowest insurance rates",
    category: "shady",
  },
  { highlight: /lowest interest rate/gi, keyword: "Lowest interest rate", category: "shady" },
  { highlight: /lowest rate/gi, keyword: "Lowest rate", category: "shady" },
  { highlight: /lowest rates/gi, keyword: "Lowest rates", category: "shady" },
  { highlight: /luxury/gi, keyword: "Luxury", category: "shady" },
  { highlight: /luxury car/gi, keyword: "Luxury car", category: "shady" },
  { highlight: /mail in order form/gi, keyword: "Mail in order form", category: "shady" },
  { highlight: /main in order form/gi, keyword: "Main in order form", category: "shady" },
  { highlight: /mark this as not junk/gi, keyword: "Mark this as not junk", category: "shady" },
  { highlight: /mass email/gi, keyword: "Mass email", category: "shady" },
  { highlight: /medical/gi, keyword: "Medical", category: "shady" },
  { highlight: /medicine/gi, keyword: "Medicine", category: "shady" },
  { highlight: /meet girls/gi, keyword: "Meet girls", category: "shady" },
  { highlight: /meet me/gi, keyword: "Meet me", category: "shady" },
  { highlight: /meet singles/gi, keyword: "Meet singles", category: "shady" },
  { highlight: /meet women/gi, keyword: "Meet women", category: "shady" },
  { highlight: /member/gi, keyword: "Member", category: "shady" },
  { highlight: /member stuff/gi, keyword: "Member stuff", category: "shady" },
  {
    highlight: /message contains disclaimer/gi,
    keyword: "Message contains disclaimer",
    category: "shady",
  },
  { highlight: /message from/gi, keyword: "Message from", category: "shady" },
  { highlight: /millionaire/gi, keyword: "Millionaire", category: "shady" },
  { highlight: /millions/gi, keyword: "Millions", category: "shady" },
  { highlight: /mlm/gi, keyword: "MLM", category: "shady" },
  { highlight: /multi-level marketing/gi, keyword: "Multi-level marketing", category: "shady" },
  { highlight: /name/gi, keyword: "Name", category: "shady" },
  { highlight: /near you/gi, keyword: "Near you", category: "shady" },
  { highlight: /never before/gi, keyword: "Never before", category: "shady" },
  { highlight: /new/gi, keyword: "New", category: "shady" },
  { highlight: /new domain extensions/gi, keyword: "New domain extensions", category: "shady" },
  { highlight: /nigerian/gi, keyword: "Nigerian", category: "shady" },
  { highlight: /no age restrictions/gi, keyword: "No age restrictions", category: "shady" },
  { highlight: /no catch/gi, keyword: "No catch", category: "shady" },
  { highlight: /no claim forms/gi, keyword: "No claim forms", category: "shady" },
  { highlight: /no cost/gi, keyword: "No cost", category: "shady" },
  { highlight: /no credit check/gi, keyword: "No credit check", category: "shady" },
  { highlight: /no credit experience/gi, keyword: "No credit experience", category: "shady" },
  { highlight: /no deposit required/gi, keyword: "No deposit required", category: "shady" },
  { highlight: /no disappointment/gi, keyword: "No disappointment", category: "shady" },
  { highlight: /no experience/gi, keyword: "No experience", category: "shady" },
  { highlight: /no fees/gi, keyword: "No fees", category: "shady" },
  { highlight: /no gimmick/gi, keyword: "No gimmick", category: "shady" },
  { highlight: /no hidden/gi, keyword: "No hidden", category: "shady" },
  { highlight: /no hidden costs/gi, keyword: "No hidden costs", category: "shady" },
  { highlight: /no hidden fees/gi, keyword: "No hidden fees", category: "shady" },
  { highlight: /no hidden сosts/gi, keyword: "No hidden сosts", category: "shady" },
  { highlight: /no interest/gi, keyword: "No interest", category: "shady" },
  { highlight: /no interests/gi, keyword: "No interests", category: "shady" },
  { highlight: /no inventory/gi, keyword: "No inventory", category: "shady" },
  { highlight: /no investment/gi, keyword: "No investment", category: "shady" },
  {
    highlight: /no investment required/gi,
    keyword: "No investment required",
    category: "shady",
  },
  { highlight: /no medical exams/gi, keyword: "No medical exams", category: "shady" },
  { highlight: /no middleman/gi, keyword: "No middleman", category: "shady" },
  { highlight: /no obligation/gi, keyword: "No obligation", category: "shady" },
  { highlight: /no payment required/gi, keyword: "No payment required", category: "shady" },
  { highlight: /no purchase necessary/gi, keyword: "No purchase necessary", category: "shady" },
  { highlight: /no questions asked/gi, keyword: "No questions asked", category: "shady" },
  { highlight: /no selling/gi, keyword: "No selling", category: "shady" },
  { highlight: /no strings attached/gi, keyword: "No strings attached", category: "shady" },
  { highlight: /no-obligation/gi, keyword: "No-obligation", category: "shady" },
  {
    highlight: /nominated bank account/gi,
    keyword: "Nominated bank account",
    category: "shady",
  },
  { highlight: /not intended/gi, keyword: "Not intended", category: "shady" },
  { highlight: /not junk/gi, keyword: "Not junk", category: "shady" },
  { highlight: /not scam/gi, keyword: "Not scam", category: "shady" },
  { highlight: /not spam/gi, keyword: "Not spam", category: "shady" },
  { highlight: /notspam/gi, keyword: "Notspam", category: "shady" },
  { highlight: /number 1/gi, keyword: "Number 1", category: "shady" },
  { highlight: /obligation/gi, keyword: "Obligation", category: "shady" },
  { highlight: /off/gi, keyword: "Off", category: "shady" },
  { highlight: /off everything/gi, keyword: "Off everything", category: "shady" },
  { highlight: /off shore/gi, keyword: "Off shore", category: "shady" },
  { highlight: /offer extended/gi, keyword: "Offer extended", category: "shady" },
  { highlight: /offers/gi, keyword: "Offers", category: "shady" },
  { highlight: /offshore/gi, keyword: "Offshore", category: "shady" },
  { highlight: /one hundred percent/gi, keyword: "One hundred percent", category: "shady" },
  { highlight: /one-time/gi, keyword: "One-time", category: "shady" },
  {
    highlight: /online biz opportunity/gi,
    keyword: "Online biz opportunity",
    category: "shady",
  },
  { highlight: /online degree/gi, keyword: "Online degree", category: "shady" },
  { highlight: /online income/gi, keyword: "Online income", category: "shady" },
  { highlight: /online job/gi, keyword: "Online job", category: "shady" },
  { highlight: /open/gi, keyword: "Open", category: "shady" },
  { highlight: /opportunity/gi, keyword: "Opportunity", category: "shady" },
  { highlight: /opt-in/gi, keyword: "Opt-in", category: "shady" },
  { highlight: /order/gi, keyword: "Order", category: "shady" },
  { highlight: /order shipped by/gi, keyword: "Order shipped by", category: "shady" },
  { highlight: /order status/gi, keyword: "Order status", category: "shady" },
  { highlight: /orders shipped by/gi, keyword: "Orders shipped by", category: "shady" },
  {
    highlight: /orders shipped by shopper/gi,
    keyword: "Orders shipped by shopper",
    category: "shady",
  },
  { highlight: /outstanding value/gi, keyword: "Outstanding value", category: "shady" },
  { highlight: /outstanding values/gi, keyword: "Outstanding values", category: "shady" },
  { highlight: /password/gi, keyword: "Password", category: "shady" },
  { highlight: /passwords/gi, keyword: "Passwords", category: "shady" },
  { highlight: /pay your bills/gi, keyword: "Pay your bills", category: "shady" },
  {
    highlight: /per (day|week|year)/gi,
    keyword: "Per day/per week/per year",
    category: "shady",
  },
  { highlight: /per month/gi, keyword: "Per month", category: "shady" },
  { highlight: /perfect/gi, keyword: "Perfect", category: "shady" },
  { highlight: /performance/gi, keyword: "Performance", category: "shady" },
  { highlight: /phone/gi, keyword: "Phone", category: "shady" },
  { highlight: /please/gi, keyword: "Please", category: "shady" },
  { highlight: /please open/gi, keyword: "Please open", category: "shady" },
  { highlight: /presently/gi, keyword: "Presently", category: "shady" },
  { highlight: /print form signature/gi, keyword: "Print form signature", category: "shady" },
  { highlight: /print from signature/gi, keyword: "Print from signature", category: "shady" },
  { highlight: /print out and fax/gi, keyword: "Print out and fax", category: "shady" },
  { highlight: /priority mail/gi, keyword: "Priority mail", category: "shady" },
  { highlight: /privately owned funds/gi, keyword: "Privately owned funds", category: "shady" },
  { highlight: /prizes/gi, keyword: "Prizes", category: "shady" },
  { highlight: /problem with shipping/gi, keyword: "Problem with shipping", category: "shady" },
  {
    highlight: /problem with your order/gi,
    keyword: "Problem with your order",
    category: "shady",
  },
  { highlight: /produced and sent out/gi, keyword: "Produced and sent out", category: "shady" },
  { highlight: /profit/gi, keyword: "Profit", category: "shady" },
  { highlight: /promise you/gi, keyword: "Promise you", category: "shady" },
  { highlight: /purchase/gi, keyword: "Purchase", category: "shady" },
  { highlight: /pure profits/gi, keyword: "Pure Profits", category: "shady" },
  { highlight: /quotes/gi, keyword: "Quotes", category: "shady" },
  { highlight: /rate/gi, keyword: "Rate", category: "shady" },
  { highlight: /real thing/gi, keyword: "Real thing", category: "shady" },
  { highlight: /rebate/gi, keyword: "Rebate", category: "shady" },
  { highlight: /reduce debt/gi, keyword: "Reduce debt", category: "shady" },
  { highlight: /refinance home/gi, keyword: "Refinance home", category: "shady" },
  { highlight: /refinanced home/gi, keyword: "Refinanced home", category: "shady" },
  { highlight: /refund/gi, keyword: "Refund", category: "shady" },
  { highlight: /regarding/gi, keyword: "Regarding", category: "shady" },
  { highlight: /removal instructions/gi, keyword: "Removal instructions", category: "shady" },
  { highlight: /removes/gi, keyword: "Removes", category: "shady" },
  { highlight: /removes wrinkles/gi, keyword: "Removes wrinkles", category: "shady" },
  { highlight: /replica watches/gi, keyword: "Replica watches", category: "shady" },
  { highlight: /request/gi, keyword: "Request", category: "shady" },
  { highlight: /request now/gi, keyword: "Request now", category: "shady" },
  { highlight: /request today/gi, keyword: "Request today", category: "shady" },
  {
    highlight: /requires initial investment/gi,
    keyword: "Requires initial investment",
    category: "shady",
  },
  { highlight: /requires investment/gi, keyword: "Requires investment", category: "shady" },
  { highlight: /reverses aging/gi, keyword: "Reverses aging", category: "shady" },
  { highlight: /risk free/gi, keyword: "Risk free", category: "shady" },
  { highlight: /rolex/gi, keyword: "Rolex", category: "shady" },
  { highlight: /round the world/gi, keyword: "Round the world", category: "shady" },
  { highlight: /s 1618/gi, keyword: "S 1618", category: "shady" },
  { highlight: /safeguard notice/gi, keyword: "Safeguard notice", category: "shady" },
  { highlight: /sale/gi, keyword: "Sale", category: "shady" },
  { highlight: /sales/gi, keyword: "Sales", category: "shady" },
  { highlight: /save/gi, keyword: "Save", category: "shady" },
  { highlight: /save big/gi, keyword: "Save big", category: "shady" },
  { highlight: /save big month/gi, keyword: "Save big month", category: "shady" },
  { highlight: /save money/gi, keyword: "Save money", category: "shady" },
  { highlight: /save now/gi, keyword: "Save now", category: "shady" },
  { highlight: /score with babes/gi, keyword: "Score with babes", category: "shady" },
  {
    highlight: /search engine optimisation/gi,
    keyword: "Search engine optimisation",
    category: "shady",
  },
  { highlight: /section 301/gi, keyword: "Section 301", category: "shady" },
  { highlight: /see for yourself/gi, keyword: "See for yourself", category: "shady" },
  { highlight: /seen on/gi, keyword: "Seen on", category: "shady" },
  { highlight: /serious/gi, keyword: "Serious", category: "shady" },
  { highlight: /serious case/gi, keyword: "Serious case", category: "shady" },
  { highlight: /serious offer/gi, keyword: "Serious offer", category: "shady" },
  { highlight: /serious only/gi, keyword: "Serious only", category: "shady" },
  { highlight: /sex/gi, keyword: "Sex", category: "shady" },
  { highlight: /shop now/gi, keyword: "Shop now", category: "shady" },
  { highlight: /shopper/gi, keyword: "Shopper", category: "shady" },
  { highlight: /shopping spree/gi, keyword: "Shopping spree", category: "shady" },
  { highlight: /snoring/gi, keyword: "Snoring", category: "shady" },
  {
    highlight: /social security number/gi,
    keyword: "Social security number",
    category: "shady",
  },
  { highlight: /soon/gi, keyword: "Soon", category: "shady" },
  { highlight: /spam/gi, keyword: "Spam", category: "shady" },
  { highlight: /spam free/gi, keyword: "Spam free", category: "shady" },
  { highlight: /special deal/gi, keyword: "Special deal", category: "shady" },
  { highlight: /special discount/gi, keyword: "Special discount", category: "shady" },
  { highlight: /special for you/gi, keyword: "Special for you", category: "shady" },
  { highlight: /special offer/gi, keyword: "Special offer", category: "shady" },
  { highlight: /stainless steel/gi, keyword: "Stainless steel", category: "shady" },
  { highlight: /stock alert/gi, keyword: "Stock alert", category: "shady" },
  {
    highlight: /stock disclaimer statement/gi,
    keyword: "Stock disclaimer statement",
    category: "shady",
  },
  { highlight: /stock pick/gi, keyword: "Stock pick", category: "shady" },
  {
    highlight: /stocks? (pick|alert)/gi,
    keyword: "Stocks/stock pick/stock alert",
    category: "shady",
  },
  { highlight: /stop calling me/gi, keyword: "Stop calling me", category: "shady" },
  { highlight: /stop emailing me/gi, keyword: "Stop emailing me", category: "shady" },
  {
    highlight: /stop further distribution/gi,
    keyword: "Stop further distribution",
    category: "shady",
  },
  { highlight: /stop snoring/gi, keyword: "Stop snoring", category: "shady" },
  { highlight: /strong buy/gi, keyword: "Strong buy", category: "shady" },
  { highlight: /stuff on sale/gi, keyword: "Stuff on sale", category: "shady" },
  { highlight: /subject to/gi, keyword: "Subject to", category: "shady" },
  { highlight: /subject to cash/gi, keyword: "Subject to cash", category: "shady" },
  { highlight: /subscribe/gi, keyword: "Subscribe", category: "shady" },
  { highlight: /subscribe for free/gi, keyword: "Subscribe for free", category: "shady" },
  { highlight: /subscribe now/gi, keyword: "Subscribe now", category: "shady" },
  { highlight: /super promo/gi, keyword: "Super promo", category: "shady" },
  { highlight: /supplies/gi, keyword: "Supplies", category: "shady" },
  { highlight: /tack action now/gi, keyword: "Tack action now", category: "shady" },
  {
    highlight: /talks about hidden charges/gi,
    keyword: "Talks about hidden charges",
    category: "shady",
  },
  { highlight: /talks about prizes/gi, keyword: "Talks about prizes", category: "shady" },
  { highlight: /tells you it’s an ad/gi, keyword: "Tells you it’s an ad", category: "shady" },
  { highlight: /terms/gi, keyword: "Terms", category: "shady" },
  { highlight: /the best rates/gi, keyword: "The best rates", category: "shady" },
  {
    highlight: /the email asks for a credit card/gi,
    keyword: "The email asks for a credit card",
    category: "shady",
  },
  { highlight: /the following form/gi, keyword: "The following form", category: "shady" },
  {
    highlight: /they make a claim or claims that they're in accordance with spam law/gi,
    keyword: "They make a claim or claims that they're in accordance with spam law",
    category: "shady",
  },
  {
    highlight: /they try to keep your money no refund/gi,
    keyword: "They try to keep your money no refund",
    category: "shady",
  },
  {
    highlight: /they’re just giving it away/gi,
    keyword: "They’re just giving it away",
    category: "shady",
  },
  { highlight: /this isn't junk/gi, keyword: "This isn't junk", category: "shady" },
  { highlight: /this isn't spam/gi, keyword: "This isn't spam", category: "shady" },
  { highlight: /this isn’t a scam/gi, keyword: "This isn’t a scam", category: "shady" },
  { highlight: /this isn’t junk/gi, keyword: "This isn’t junk", category: "shady" },
  { highlight: /this isn’t spam/gi, keyword: "This isn’t spam", category: "shady" },
  { highlight: /timeshare/gi, keyword: "Timeshare", category: "shady" },
  { highlight: /timeshare offers/gi, keyword: "Timeshare offers", category: "shady" },
  { highlight: /traffic/gi, keyword: "Traffic", category: "shady" },
  { highlight: /trial unlimited/gi, keyword: "Trial unlimited", category: "shady" },
  { highlight: /u.s. dollars/gi, keyword: "U.S. dollars", category: "shady" },
  { highlight: /undisclosed/gi, keyword: "Undisclosed", category: "shady" },
  { highlight: /undisclosed recipient/gi, keyword: "Undisclosed recipient", category: "shady" },
  { highlight: /university diplomas/gi, keyword: "University diplomas", category: "shady" },
  { highlight: /unsecured credit/gi, keyword: "Unsecured credit", category: "shady" },
  { highlight: /unsecured debt/gi, keyword: "Unsecured debt", category: "shady" },
  { highlight: /unsolicited/gi, keyword: "Unsolicited", category: "shady" },
  { highlight: /unsubscribe/gi, keyword: "Unsubscribe", category: "shady" },
  { highlight: /urgent response/gi, keyword: "Urgent response", category: "shady" },
  { highlight: /us dollars|euros/gi, keyword: "US dollars / Euros", category: "shady" },
  { highlight: /vacation/gi, keyword: "Vacation", category: "shady" },
  { highlight: /vacation offers/gi, keyword: "Vacation offers", category: "shady" },
  { highlight: /valium/gi, keyword: "Valium", category: "shady" },
  { highlight: /viagra/gi, keyword: "Viagra", category: "shady" },
  { highlight: /vicodin/gi, keyword: "Vicodin", category: "shady" },
  { highlight: /vip/gi, keyword: "VIP", category: "shady" },
  { highlight: /visit our website/gi, keyword: "Visit our website", category: "shady" },
  { highlight: /wants credit card/gi, keyword: "Wants credit card", category: "shady" },
  { highlight: /warranty expired/gi, keyword: "Warranty expired", category: "shady" },
  { highlight: /we hate spam/gi, keyword: "We hate spam", category: "shady" },
  { highlight: /we honor all/gi, keyword: "We honor all", category: "shady" },
  { highlight: /website visitors/gi, keyword: "Website visitors", category: "shady" },
  { highlight: /weekend getaway/gi, keyword: "Weekend getaway", category: "shady" },
  { highlight: /weight loss/gi, keyword: "Weight loss", category: "shady" },
  { highlight: /what’s keeping you\?/gi, keyword: "What’s keeping you?", category: "shady" },
  { highlight: /while available/gi, keyword: "While available", category: "shady" },
  { highlight: /while in stock/gi, keyword: "While in stock", category: "shady" },
  { highlight: /while stocks last/gi, keyword: "While stocks last", category: "shady" },
  { highlight: /while you sleep/gi, keyword: "While you sleep", category: "shady" },
  { highlight: /who really wins\?/gi, keyword: "Who really wins?", category: "shady" },
  { highlight: /win/gi, keyword: "Win", category: "shady" },
  { highlight: /winner/gi, keyword: "Winner", category: "shady" },
  { highlight: /winning/gi, keyword: "Winning", category: "shady" },
  { highlight: /won/gi, keyword: "Won", category: "shady" },
  { highlight: /xanax/gi, keyword: "Xanax", category: "shady" },
  { highlight: /xxx/gi, keyword: "XXX", category: "shady" },
  { highlight: /you have been chosen/gi, keyword: "You have been chosen", category: "shady" },
  {
    highlight: /you have been selected/gi,
    keyword: "You have been selected",
    category: "shady",
  },
  { highlight: /your chance/gi, keyword: "Your chance", category: "shady" },
  { highlight: /your status/gi, keyword: "Your status", category: "shady" },
  { highlight: /zero chance/gi, keyword: "Zero chance", category: "shady" },
  { highlight: /zero percent/gi, keyword: "Zero percent", category: "shady" },
  { highlight: /zero risk/gi, keyword: "Zero risk", category: "shady" },
  { highlight: /#1/gi, keyword: "#1", category: "overpromise" },
  { highlight: /[0-9]+%/gi, keyword: "%", category: "overpromise" },
  { highlight: /[0-9]+% free/gi, keyword: "% free", category: "overpromise" },
  { highlight: /[0-9]+% satisfied/gi, keyword: "% Satisfied", category: "overpromise" },
  { highlight: /[0-9]+%/gi, keyword: "0%", category: "overpromise" },
  { highlight: /[0-9]+% risk/gi, keyword: "0% risk", category: "overpromise" },
  { highlight: /100%/gi, keyword: "100%", category: "overpromise" },
  { highlight: /100% free/gi, keyword: "100% free", category: "overpromise" },
  { highlight: /100% more/gi, keyword: "100% more", category: "overpromise" },
  { highlight: /100% off/gi, keyword: "100% off", category: "overpromise" },
  { highlight: /100% satisfied/gi, keyword: "100% satisfied", category: "overpromise" },
  { highlight: /99.90%/gi, keyword: "99.90%", category: "overpromise" },
  { highlight: /99%/gi, keyword: "99%", category: "overpromise" },
  { highlight: /access for free/gi, keyword: "Access for free", category: "overpromise" },
  { highlight: /additional income/gi, keyword: "Additional income", category: "overpromise" },
  { highlight: /amazed/gi, keyword: "Amazed", category: "overpromise" },
  { highlight: /amazing/gi, keyword: "Amazing", category: "overpromise" },
  { highlight: /amazing offer/gi, keyword: "Amazing offer", category: "overpromise" },
  { highlight: /amazing stuff/gi, keyword: "Amazing stuff", category: "overpromise" },
  { highlight: /be amazed/gi, keyword: "Be amazed", category: "overpromise" },
  { highlight: /be surprised/gi, keyword: "Be surprised", category: "overpromise" },
  { highlight: /be your own boss/gi, keyword: "Be your own boss", category: "overpromise" },
  { highlight: /believe me/gi, keyword: "Believe me", category: "overpromise" },
  { highlight: /best bargain/gi, keyword: "Best bargain", category: "overpromise" },
  { highlight: /best deal/gi, keyword: "Best deal", category: "overpromise" },
  { highlight: /best offer/gi, keyword: "Best offer", category: "overpromise" },
  { highlight: /best price/gi, keyword: "Best price", category: "overpromise" },
  { highlight: /best rates/gi, keyword: "Best rates", category: "overpromise" },
  { highlight: /big bucks/gi, keyword: "Big bucks", category: "overpromise" },
  { highlight: /bonus/gi, keyword: "Bonus", category: "overpromise" },
  { highlight: /boss/gi, keyword: "Boss", category: "overpromise" },
  { highlight: /can’t live without/gi, keyword: "Can’t live without", category: "overpromise" },
  { highlight: /cancel/gi, keyword: "Cancel", category: "overpromise" },
  { highlight: /consolidate debt/gi, keyword: "Consolidate debt", category: "overpromise" },
  { highlight: /double your cash/gi, keyword: "Double your cash", category: "overpromise" },
  { highlight: /double your income/gi, keyword: "Double your income", category: "overpromise" },
  {
    highlight: /drastically reduced/gi,
    keyword: "Drastically reduced",
    category: "overpromise",
  },
  { highlight: /earn extra cash/gi, keyword: "Earn extra cash", category: "overpromise" },
  { highlight: /earn money/gi, keyword: "Earn money", category: "overpromise" },
  {
    highlight: /eliminate bad credit/gi,
    keyword: "Eliminate bad credit",
    category: "overpromise",
  },
  { highlight: /expect to earn/gi, keyword: "Expect to earn", category: "overpromise" },
  { highlight: /extra/gi, keyword: "Extra", category: "overpromise" },
  { highlight: /extra cash/gi, keyword: "Extra cash", category: "overpromise" },
  { highlight: /extra income/gi, keyword: "Extra income", category: "overpromise" },
  { highlight: /fantastic/gi, keyword: "Fantastic", category: "overpromise" },
  { highlight: /fantastic deal/gi, keyword: "Fantastic deal", category: "overpromise" },
  { highlight: /fantastic offer/gi, keyword: "Fantastic offer", category: "overpromise" },
  { highlight: /fast/gi, keyword: "FAST", category: "overpromise" },
  { highlight: /fast cash/gi, keyword: "Fast cash", category: "overpromise" },
  { highlight: /financial freedom/gi, keyword: "Financial freedom", category: "overpromise" },
  { highlight: /free access/gi, keyword: "Free access", category: "overpromise" },
  { highlight: /free consultation/gi, keyword: "Free consultation", category: "overpromise" },
  { highlight: /free gift/gi, keyword: "Free gift", category: "overpromise" },
  { highlight: /free hosting/gi, keyword: "Free hosting", category: "overpromise" },
  { highlight: /free info/gi, keyword: "Free info", category: "overpromise" },
  { highlight: /free investment/gi, keyword: "Free investment", category: "overpromise" },
  { highlight: /free membership/gi, keyword: "Free membership", category: "overpromise" },
  { highlight: /free money/gi, keyword: "Free money", category: "overpromise" },
  { highlight: /free preview/gi, keyword: "Free preview", category: "overpromise" },
  { highlight: /free quote/gi, keyword: "Free quote", category: "overpromise" },
  { highlight: /free trial/gi, keyword: "Free trial", category: "overpromise" },
  { highlight: /full refund/gi, keyword: "Full refund", category: "overpromise" },
  { highlight: /get out of debt/gi, keyword: "Get out of debt", category: "overpromise" },
  { highlight: /giveaway/gi, keyword: "Giveaway", category: "overpromise" },
  { highlight: /guaranteed/gi, keyword: "Guaranteed", category: "overpromise" },
  { highlight: /increase sales/gi, keyword: "Increase sales", category: "overpromise" },
  { highlight: /increase traffic/gi, keyword: "Increase traffic", category: "overpromise" },
  { highlight: /incredible deal/gi, keyword: "Incredible deal", category: "overpromise" },
  { highlight: /join billions/gi, keyword: "Join billions", category: "overpromise" },
  { highlight: /join millions/gi, keyword: "Join millions", category: "overpromise" },
  {
    highlight: /join millions of americans/gi,
    keyword: "Join millions of Americans",
    category: "overpromise",
  },
  { highlight: /join thousands/gi, keyword: "Join thousands", category: "overpromise" },
  { highlight: /lower rates/gi, keyword: "Lower rates", category: "overpromise" },
  { highlight: /lowest price/gi, keyword: "Lowest price", category: "overpromise" },
  { highlight: /make money/gi, keyword: "Make money", category: "overpromise" },
  { highlight: /million/gi, keyword: "Million", category: "overpromise" },
  { highlight: /million dollars/gi, keyword: "Million dollars", category: "overpromise" },
  { highlight: /miracle/gi, keyword: "Miracle", category: "overpromise" },
  { highlight: /money back/gi, keyword: "Money back", category: "overpromise" },
  { highlight: /month trial offer/gi, keyword: "Month trial offer", category: "overpromise" },
  {
    highlight: /more internet traffic/gi,
    keyword: "More Internet Traffic",
    category: "overpromise",
  },
  { highlight: /number one/gi, keyword: "Number one", category: "overpromise" },
  { highlight: /once in a lifetime/gi, keyword: "Once in a lifetime", category: "overpromise" },
  {
    highlight: /one hundred percent guaranteed/gi,
    keyword: "One hundred percent guaranteed",
    category: "overpromise",
  },
  { highlight: /one time/gi, keyword: "One time", category: "overpromise" },
  { highlight: /pennies a day/gi, keyword: "Pennies a day", category: "overpromise" },
  { highlight: /potential earnings/gi, keyword: "Potential earnings", category: "overpromise" },
  { highlight: /prize/gi, keyword: "Prize", category: "overpromise" },
  { highlight: /promise/gi, keyword: "Promise", category: "overpromise" },
  { highlight: /pure profit/gi, keyword: "Pure profit", category: "overpromise" },
  { highlight: /risk-free/gi, keyword: "Risk-free", category: "overpromise" },
  {
    highlight: /satisfaction guaranteed/gi,
    keyword: "Satisfaction guaranteed",
    category: "overpromise",
  },
  { highlight: /save big money/gi, keyword: "Save big money", category: "overpromise" },
  { highlight: /save up to/gi, keyword: "Save up to", category: "overpromise" },
  { highlight: /special promotion/gi, keyword: "Special promotion", category: "overpromise" },
  { highlight: /the best/gi, keyword: "The best", category: "overpromise" },
  { highlight: /thousands/gi, keyword: "Thousands", category: "overpromise" },
  { highlight: /unbeatable offer/gi, keyword: "Unbeatable offer", category: "overpromise" },
  { highlight: /unbelievable/gi, keyword: "Unbelievable", category: "overpromise" },
  { highlight: /unlimited/gi, keyword: "Unlimited", category: "overpromise" },
  { highlight: /unlimited trial/gi, keyword: "Unlimited trial", category: "overpromise" },
  { highlight: /wonderful/gi, keyword: "Wonderful", category: "overpromise" },
  {
    highlight: /you will not believe your eyes/gi,
    keyword: "You will not believe your eyes",
    category: "overpromise",
  },
  { highlight: /[\$£€¥]+[0-9\.\,]+/gi, keyword: "$$$", category: "money" },
  { highlight: /[0-9\.\,]+[\$£€¥]+/gi, keyword: "€€€", category: "money" },
  { highlight: /[\$£€¥]{2,}/gi, keyword: "£££", category: "money" },
  { highlight: /[0-9\.,]+%( off)?/gi, keyword: "50% off", category: "money" },
  { highlight: /a few bob/gi, keyword: "A few bob", category: "money" },
  { highlight: /accept cash cards/gi, keyword: "Accept cash cards", category: "money" },
  { highlight: /accept credit cards/gi, keyword: "Accept credit cards", category: "money" },
  { highlight: /affordable/gi, keyword: "Affordable", category: "money" },
  { highlight: /affordable deal/gi, keyword: "Affordable deal", category: "money" },
  { highlight: /avoid bankruptcy/gi, keyword: "Avoid bankruptcy", category: "money" },
  { highlight: /bad credit/gi, keyword: "Bad credit", category: "money" },
  { highlight: /bank/gi, keyword: "Bank", category: "money" },
  { highlight: /bankruptcy/gi, keyword: "Bankruptcy", category: "money" },
  { highlight: /bargain/gi, keyword: "Bargain", category: "money" },
  { highlight: /billing/gi, keyword: "Billing", category: "money" },
  { highlight: /billing address/gi, keyword: "Billing address", category: "money" },
  { highlight: /billion/gi, keyword: "Billion", category: "money" },
  { highlight: /billion dollars/gi, keyword: "Billion dollars", category: "money" },
  { highlight: /billionaire/gi, keyword: "Billionaire", category: "money" },
  { highlight: /card accepted/gi, keyword: "Card accepted", category: "money" },
  { highlight: /cards accepted/gi, keyword: "Cards accepted", category: "money" },
  { highlight: /cash/gi, keyword: "Cash", category: "money" },
  { highlight: /cash bonus/gi, keyword: "Cash bonus", category: "money" },
  { highlight: /cash out/gi, keyword: "Cash out", category: "money" },
  { highlight: /cash-out/gi, keyword: "Cash-out", category: "money" },
  { highlight: /cashcashcash/gi, keyword: "Cashcashcash", category: "money" },
  { highlight: /casino/gi, keyword: "Casino", category: "money" },
  { highlight: /cents on the dollar/gi, keyword: "Cents on the dollar", category: "money" },
  { highlight: /check/gi, keyword: "Check", category: "money" },
  { highlight: /check or money order/gi, keyword: "Check or money order", category: "money" },
  { highlight: /claim your discount/gi, keyword: "Claim your discount", category: "money" },
  { highlight: /cost/gi, keyword: "Cost", category: "money" },
  { highlight: /costs/gi, keyword: "Costs", category: "money" },
  { highlight: /credit/gi, keyword: "Credit", category: "money" },
  { highlight: /credit bureaus/gi, keyword: "Credit bureaus", category: "money" },
  { highlight: /credit card/gi, keyword: "Credit card", category: "money" },
  { highlight: /credit card offers/gi, keyword: "Credit card offers", category: "money" },
  { highlight: /credit or debit/gi, keyword: "Credit or Debit", category: "money" },
  { highlight: /deal/gi, keyword: "Deal", category: "money" },
  { highlight: /debt/gi, keyword: "Debt", category: "money" },
  { highlight: /discount/gi, keyword: "Discount", category: "money" },
  { highlight: /dollars/gi, keyword: "Dollars", category: "money" },
  { highlight: /double your/gi, keyword: "Double your", category: "money" },
  { highlight: /double your wealth/gi, keyword: "Double your wealth", category: "money" },
  { highlight: /earn/gi, keyword: "Earn", category: "money" },
  { highlight: /earn [\$£€¥]+/gi, keyword: "Earn $", category: "money" },
  { highlight: /earn cash/gi, keyword: "Earn cash", category: "money" },
  { highlight: /earn extra income/gi, keyword: "Earn extra income", category: "money" },
  { highlight: /earn from home/gi, keyword: "Earn from home", category: "money" },
  { highlight: /earn monthly/gi, keyword: "Earn monthly", category: "money" },
  { highlight: /earn per month/gi, keyword: "Earn per month", category: "money" },
  { highlight: /earn per week/gi, keyword: "Earn per week", category: "money" },
  { highlight: /earn your degree/gi, keyword: "Earn your degree", category: "money" },
  { highlight: /easy income/gi, keyword: "Easy income", category: "money" },
  { highlight: /easy terms/gi, keyword: "Easy terms", category: "money" },
  { highlight: /f r e e/gi, keyword: "F r e e", category: "money" },
  { highlight: /for free/gi, keyword: "For free", category: "money" },
  { highlight: /for just [\$£€¥]+/gi, keyword: "For just $", category: "money" },
  { highlight: /for just [\$£€¥]+[0-9]+/gi, keyword: "For just $ (amount)", category: "money" },
  { highlight: /for just [\$£€¥]+xxx/gi, keyword: "For just $xxx", category: "money" },
  { highlight: /get money/gi, keyword: "Get Money", category: "money" },
  { highlight: /get your money/gi, keyword: "Get your money", category: "money" },
  { highlight: /hidden assets/gi, keyword: "Hidden assets", category: "money" },
  { highlight: /huge discount/gi, keyword: "Huge discount", category: "money" },
  { highlight: /income/gi, keyword: "Income", category: "money" },
  { highlight: /income from home/gi, keyword: "Income from home", category: "money" },
  { highlight: /increase revenue/gi, keyword: "Increase revenue", category: "money" },
  {
    highlight: /increase (sales|traffic)/gi,
    keyword: "Increase sales/traffic",
    category: "money",
  },
  { highlight: /increase your chances/gi, keyword: "Increase your chances", category: "money" },
  { highlight: /initial investment/gi, keyword: "Initial investment", category: "money" },
  { highlight: /instant earnings/gi, keyword: "Instant earnings", category: "money" },
  { highlight: /instant income/gi, keyword: "Instant income", category: "money" },
  { highlight: /insurance/gi, keyword: "Insurance", category: "money" },
  { highlight: /investment/gi, keyword: "Investment", category: "money" },
  { highlight: /investment advice/gi, keyword: "Investment advice", category: "money" },
  { highlight: /lifetime/gi, keyword: "Lifetime", category: "money" },
  { highlight: /loans/gi, keyword: "Loans", category: "money" },
  { highlight: /make [\$£€¥]+/gi, keyword: "Make $", category: "money" },
  { highlight: /money/gi, keyword: "Money", category: "money" },
  { highlight: /money making/gi, keyword: "Money making", category: "money" },
  { highlight: /money-back guarantee/gi, keyword: "Money-back guarantee", category: "money" },
  { highlight: /money-making/gi, keyword: "Money-making", category: "money" },
  { highlight: /monthly payment/gi, keyword: "Monthly payment", category: "money" },
  { highlight: /mortgage/gi, keyword: "Mortgage", category: "money" },
  { highlight: /mortgage rates/gi, keyword: "Mortgage rates", category: "money" },
  { highlight: /offer/gi, keyword: "Offer", category: "money" },
  {
    highlight: /one hundred percent free/gi,
    keyword: "One hundred percent free",
    category: "money",
  },
  { highlight: /only [\$£€¥]+/gi, keyword: "Only $", category: "money" },
  { highlight: /price/gi, keyword: "Price", category: "money" },
  { highlight: /price protection/gi, keyword: "Price protection", category: "money" },
  { highlight: /prices/gi, keyword: "Prices", category: "money" },
  { highlight: /profits/gi, keyword: "Profits", category: "money" },
  { highlight: /quote/gi, keyword: "Quote", category: "money" },
  { highlight: /rates/gi, keyword: "Rates", category: "money" },
  { highlight: /refinance/gi, keyword: "Refinance", category: "money" },
  { highlight: /save [\$£€¥]+/gi, keyword: "Save $", category: "money" },
  { highlight: /serious cash/gi, keyword: "Serious cash", category: "money" },
  { highlight: /subject to credit/gi, keyword: "Subject to credit", category: "money" },
  { highlight: /us dollars/gi, keyword: "US dollars", category: "money" },
  { highlight: /why pay more\?/gi, keyword: "Why pay more?", category: "money" },
  { highlight: /your income/gi, keyword: "Your income", category: "money" },
  { highlight: /acceptance/gi, keyword: "Acceptance", category: "unnatural" },
  { highlight: /accordingly/gi, keyword: "Accordingly", category: "unnatural" },
  {
    highlight: /account-based marketing (abm)/gi,
    keyword: "Account-based marketing (ABM)",
    category: "unnatural",
  },
  { highlight: /accounts/gi, keyword: "Accounts", category: "unnatural" },
  { highlight: /addresses/gi, keyword: "Addresses", category: "unnatural" },
  { highlight: /addresses on cd/gi, keyword: "Addresses on CD", category: "unnatural" },
  { highlight: /beverage/gi, keyword: "Beverage", category: "unnatural" },
  {
    highlight: /confidentiality on all orders/gi,
    keyword: "Confidentiality on all orders",
    category: "unnatural",
  },
  {
    highlight: /confidentially on all orders/gi,
    keyword: "Confidentially on all orders",
    category: "unnatural",
  },
  { highlight: /content marketing/gi, keyword: "Content marketing", category: "unnatural" },
  { highlight: /dear(est)? (.+@.+)/gi, keyword: "Dear [email address]", category: "unnatural" },
  {
    highlight: /dear(est)? (email|friend|somebody)/gi,
    keyword: "Dear [email/friend/somebody]",
    category: "unnatural",
  },
  { highlight: /dear [first name]/gi, keyword: "Dear [first name]", category: "unnatural" },
  { highlight: /dear [wrong name]/gi, keyword: "Dear [wrong name]", category: "unnatural" },
  { highlight: /digital marketing/gi, keyword: "Digital marketing", category: "unnatural" },
  { highlight: /dormant/gi, keyword: "Dormant", category: "unnatural" },
  { highlight: /email extractor/gi, keyword: "Email extractor", category: "unnatural" },
  { highlight: /email harvest/gi, keyword: "Email harvest", category: "unnatural" },
  { highlight: /email marketing/gi, keyword: "Email marketing", category: "unnatural" },
  { highlight: /extract email/gi, keyword: "Extract email", category: "unnatural" },
  { highlight: /form/gi, keyword: "Form", category: "unnatural" },
  { highlight: /freedom/gi, keyword: "Freedom", category: "unnatural" },
  { highlight: /friend/gi, keyword: "Friend", category: "unnatural" },
  { highlight: /here/gi, keyword: "Here", category: "unnatural" },
  { highlight: /hidden/gi, keyword: "Hidden", category: "unnatural" },
  { highlight: /home/gi, keyword: "Home", category: "unnatural" },
  { highlight: /home based/gi, keyword: "Home based", category: "unnatural" },
  { highlight: /home employment/gi, keyword: "Home employment", category: "unnatural" },
  { highlight: /home-based/gi, keyword: "Home-based", category: "unnatural" },
  { highlight: /home-based business/gi, keyword: "Home-based business", category: "unnatural" },
  { highlight: /homebased business/gi, keyword: "Homebased business", category: "unnatural" },
  {
    highlight: /if you no longer wish to receive/gi,
    keyword: "If you no longer wish to receive",
    category: "unnatural",
  },
  {
    highlight: /important information regarding/gi,
    keyword: "Important information regarding",
    category: "unnatural",
  },
  {
    highlight: /in accordance with laws/gi,
    keyword: "In accordance with laws",
    category: "unnatural",
  },
  { highlight: /increase your sales/gi, keyword: "Increase your sales", category: "unnatural" },
  { highlight: /internet market/gi, keyword: "Internet market", category: "unnatural" },
  { highlight: /leave/gi, keyword: "Leave", category: "unnatural" },
  { highlight: /lose/gi, keyword: "Lose", category: "unnatural" },
  { highlight: /maintained/gi, keyword: "Maintained", category: "unnatural" },
  { highlight: /marketing/gi, keyword: "Marketing", category: "unnatural" },
  { highlight: /marketing solution/gi, keyword: "Marketing solution", category: "unnatural" },
  { highlight: /marketing solutions/gi, keyword: "Marketing solutions", category: "unnatural" },
  { highlight: /medium/gi, keyword: "Medium", category: "unnatural" },
  { highlight: /message contains/gi, keyword: "Message contains", category: "unnatural" },
  {
    highlight: /multi level marketing/gi,
    keyword: "Multi level marketing",
    category: "unnatural",
  },
  { highlight: /never/gi, keyword: "Never", category: "unnatural" },
  { highlight: /one time mailing/gi, keyword: "One time mailing", category: "unnatural" },
  { highlight: /online marketing/gi, keyword: "Online marketing", category: "unnatural" },
  { highlight: /online pharmacy/gi, keyword: "Online pharmacy", category: "unnatural" },
  { highlight: /opt in/gi, keyword: "Opt in", category: "unnatural" },
  { highlight: /per day/gi, keyword: "Per day", category: "unnatural" },
  { highlight: /per week/gi, keyword: "Per week", category: "unnatural" },
  { highlight: /pre-approved/gi, keyword: "Pre-approved", category: "unnatural" },
  { highlight: /problem/gi, keyword: "Problem", category: "unnatural" },
  { highlight: /removal/gi, keyword: "Removal", category: "unnatural" },
  { highlight: /remove/gi, keyword: "Remove", category: "unnatural" },
  { highlight: /reserves the right/gi, keyword: "Reserves the right", category: "unnatural" },
  { highlight: /reverses/gi, keyword: "Reverses", category: "unnatural" },
  { highlight: /sample/gi, keyword: "Sample", category: "unnatural" },
  { highlight: /satisfaction/gi, keyword: "Satisfaction", category: "unnatural" },
  { highlight: /score/gi, keyword: "Score", category: "unnatural" },
  { highlight: /search engine/gi, keyword: "Search engine", category: "unnatural" },
  {
    highlight: /search engine listings/gi,
    keyword: "Search engine listings",
    category: "unnatural",
  },
  { highlight: /search engines/gi, keyword: "Search engines", category: "unnatural" },
  { highlight: /sent in compliance/gi, keyword: "Sent in compliance", category: "unnatural" },
  { highlight: /solution/gi, keyword: "Solution", category: "unnatural" },
  { highlight: /stop/gi, keyword: "Stop", category: "unnatural" },
  { highlight: /success/gi, keyword: "Success", category: "unnatural" },
  { highlight: /teen/gi, keyword: "Teen", category: "unnatural" },
  {
    highlight: /terms and conditions/gi,
    keyword: "Terms and conditions",
    category: "unnatural",
  },
  { highlight: /warranty/gi, keyword: "Warranty", category: "unnatural" },
  { highlight: /web traffic/gi, keyword: "Web traffic", category: "unnatural" },
  { highlight: /wife/gi, keyword: "Wife", category: "unnatural" },
  { highlight: /work at home/gi, keyword: "Work at home", category: "unnatural" },
  { highlight: /work from home/gi, keyword: "Work from home", category: "unnatural" },
].reverse();

export { BASE_URL, CLIENT_ID_GCP, DATA_SPAM };
